### ISSUE TITLE
Including platform-specific styles

### ISSUE THREAD

**Issue by amjd** [NativeScript/nativescript-dev-less#1]
How can we include platform specific styles (`platform.android.css` and `platform.ios.css`) while using nativescript-dev-less?

With plain CSS, the code looks like this:

``` css
﻿@import { url('~/platform.css') };
```

Also, what does the `~` represents in the above code? And is there anything special about the name `platform.css`, since the file doesn't actually exist?

**Comment by Kobzol** [comment]
As for your second question, you can read the answer in the official docs - http://docs.nativescript.org/angular/tutorial/ng-chapter-2#25-global-css.
The platform.ios.css becomes platforms/ios/platform.css and platform.android.css becomes platforms/android/platform.css, thus the import will be resolved correctly.
The import should work in LESS and CSS, the `~` means relative to the root.

**Comment by radeva** [comment]
Closed due to inactivity

**Comment by PanayotCankov** [comment]
P. S. Soon this should work in web pack, and the `~/` will mean relative to the `app` folder while `~` (without following `/`) will mean in the `node_modules`.
