### ISSUE TITLE
Does not correctly handle asynchronicity

### ISSUE THREAD

**Issue by chimon2000** [NativeScript/nativescript-dev-less#3]
## Reproduce Test Steps
1. Attempt to transpile multiple less files that depend on variables.less
## Expected Outcome

Files should transpile with correct filename.
## Actual Outcome

Files transpile with the last iterated filename.

I believe this is because the npm package has not been updated.

**Comment by binarynate** [comment]
I'm running into this issue too on OS X and am currently debugging. @chimon2000, did you find a solution? If I find what's causing the issue, I'll put up a PR.

**Comment by hdeshev** [comment]
The fix should be live with version 0.0.10.
